[package]
name = "hdl-cat-circuit"
description = "Circuit as symmetric monoidal category built on comp-cat-rs and hdl-cat-ir"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
comp-cat-rs.workspace = true
hdl-cat-error.workspace = true
hdl-cat-kind.workspace = true
hdl-cat-ir.workspace = true
hdl-cat-bits.workspace = true

[lints]
workspace = true
