[package]
name = "hdl-cat"
description = "Umbrella crate re-exporting the hdl-cat workspace"
version = "0.9.1"
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
hdl-cat-error.workspace = true
hdl-cat-bits.workspace = true
hdl-cat-kind.workspace = true
hdl-cat-signal.workspace = true
hdl-cat-ir.workspace = true
hdl-cat-circuit.workspace = true
hdl-cat-sync.workspace = true
hdl-cat-sim.workspace = true
hdl-cat-verilog.workspace = true
hdl-cat-circom.workspace = true
hdl-cat-macros.workspace = true
hdl-cat-std.workspace = true

[lints]
workspace = true
